[server]
port = ":2022"                              # server address
https = false                               # whether enable https
certPath = "./certificate/certificate.pem"  # The certificate path
keyPath = "./certificate/privatekey.pem"    # The key path

[database]
type = "mongo"                              # only support mongo
host = "127.0.0.1"                          # mongo ip
port = 27017                                # mongo port
user = ""                                   # mongo username
password = ""                               # mongo password
database = "ShadowEditor"                   # mongo database name

[mysql]
uri = "root:miaoxiangtest@root@tcp(120.26.81.101:3306)/fastadmin?charset=utf8mb4&parseTime=True&loc=Local"
max_open_conns = 20
max_idle_conns = 10

[authority]
enabled = false                             # enable authority
expires = 120                               # login time, minutes, only support integer 
secret_key = "Welcome ---------"            # secret_key is used to encrypt credentials

[upload]
max_size = 1000000000                       # max upload file size

[path]
public_dir = "./public"                     # The directory that contains index.html. 
                                            # Path `./public/Upload` need write authority.
log_dir = "./logs"                          # The directory that contains log files. Need write authority.

[log]
file = "./logs/ShadowEditor.txt"

[cloudSpaceServer]
#测试环境
#address = "120.26.81.101"
#port = 22
#username = "root"
#password = "Miaoxiang@996"
#path = "/home/cloudSpace/"  # The path of cloudSpace
address = "120.26.47.168"
port = 22
username = "root"
password = "Miaoda@666"
path = "/home/cloudSpace/"  # The path of cloudSpace